### ISSUE TITLE
Auto build and deploy

### ISSUE THREAD

**Issue by tabuna** [livewire/docs#15]
Hey.

I noticed that we have to collect the project with every change in the manual,
 we can avoid it using `travis-ci`

Not long ago, I did this with Jigsaw and my memories are fresh.
Are you interested in this?

It's very simple, you only need to specify the key.

```yaml
language: php

php:
  - 7.3

node_js:
  - 10

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest

script:
  - npm install
  - npm run production
  - vendor/bin/jigsaw build production

deploy:
  local_dir: build_production
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
```

Each time the main repository changes, the handler will be activated which collects the project and uploads the changes to the `gh-pages` branch.
